[package]
name = "chess_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
abes_nice_things = { path = "../abes_nice_things", features = ["ai"] }